# Generated by Django 6.0.4 on 2026-04-30 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='locais.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cep', models.TextField()),
                ('logradouro', models.TextField()),
                ('numero', models.IntegerField()),
                ('complemento', models.TextField(blank=True, null=True)),
                ('bairro', models.TextField()),
                ('site', models.TextField(blank=True, null=True)),
                ('horario', models.TextField()),
                ('telefone', models.TextField()),
                ('id_cidade', models.ForeignKey(db_column='id_cidade', on_delete=django.db.models.deletion.CASCADE, to='locais.cidade')),
            ],
        ),
    ]
