# Generated by Django 6.0.4 on 2026-05-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='local',
            name='longitude',
        ),
    ]
