# Generated by Django 6.0.4 on 2026-04-30 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id_residuo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Residuo_Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_local', models.ForeignKey(db_column='id_local', on_delete=django.db.models.deletion.CASCADE, to='locais.local')),
                ('id_residuo', models.ForeignKey(db_column='id_residuo', on_delete=django.db.models.deletion.CASCADE, to='residuos.residuo')),
            ],
        ),
    ]
