# Generated by Django 6.0.4 on 2026-05-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residuo',
            name='info',
            field=models.TextField(default='info'),
            preserve_default=False,
        ),
    ]
